name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    if: github.repository == 'gatling/kotlin-plugin'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true -Xss100M"
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Prepare environment
        env:
          SONATYPE_SBT: ${{ secrets.SONATYPE_SBT }}
          SONATYPE_PGP_SECRET: ${{ secrets.SONATYPE_PGP_SECRET }}
        run: |
          mkdir --parents ~/.sbt/1.0 || true
          echo "$SONATYPE_SBT" > ~/.sbt/1.0/sonatype.sbt
          echo -n "$SONATYPE_PGP_SECRET" | base64 --decode | gpg --batch --import

      #     - name: Cache
      #       No cache for release! We want clean and full release!

      - name: Release
        id: release
        env:
          PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PASSPHRASE }}
        run: sbt compile ^scripted publishSigned sonatypePrepare sonatypeBundleUpload sonatypeClose
        # We don't execute sonatypePromote (or sonatypeRelease): the staging repository must then be promoted manually

      - name: Message
        run: echo "Do NOT forget to release the staging repository on https://s01.oss.sonatype.org"
