name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release:
    if: github.repository == 'gatling/kotlin-plugin'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true -Xss100M"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Prepare environment
        env:
          SONATYPE_SBT: ${{ secrets.SONATYPE_SBT }}
          SONATYPE_PGP_SECRET: ${{ secrets.SONATYPE_PGP_SECRET }}
        run: |
          mkdir --parents ~/.sbt/1.0 || true
          echo "$SONATYPE_SBT" > ~/.sbt/1.0/sonatype.sbt
          echo -n "$SONATYPE_PGP_SECRET" | base64 --decode | gpg --batch --import

#     - name: Cache
#       No cache for release! We want clean and full release!

      - name: Release
        id: release
        env:
          PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PASSPHRASE }}
        run: |
          sbt "release with-defaults"
          echo "version=$(cat target/release-info)" # DO NOT REMOVE, because of bad parsing for outputs
          echo "version=$(cat target/release-info)" >> $GITHUB_OUTPUT
